#! /bin/sh
[ -z "$(echo -e)" ] && ECHO=("echo" "-e") || ECHO=("echo")
while :
do
	clear
	neofetch --ascii
	${ECHO[@]} "\033[0;36m\n\n  Welcome!\n\n   What do you want to open?\n\n\033[0;34m    [d] start the x server\n    [t] continue to tty\n    [T] open tmux in the ttyn\n    [w] Start wpa_supplicant\n\n\t"
	read xtTw
	case $xtTw in
		[d]* ) cp ~/.dwmxinit ~/.xinitrc -f && startx;;
		[t]* ) exit;;
		[T]* ) tmux;;
		[w]* ) sudo wpa_supplicant -B -i wlp3s0 -c /etc/wpa_supplicant/wpa_supplicant.conf -Dwext;;
		* ) $ECHO "invalid response, defaulting to tty";;
	esac
done
